# Generated by Django 5.0.2 on 2024-02-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_att',
            new_name='created_at',
        ),
    ]
